### ISSUE TITLE
Updating Deployment with API keys as authentication method not working

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/astro-cli#1076]
**Describe the bug**

If I want to authenticate to Astro using Deployment API keys, I can't update a Deployment with `astro deployment update --deployment-file my-file.yml`.

**What CLI Version did you experience this bug?**

1.10.0

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?** macOs

**🪜 Steps To Reproduce**

1. Go to cloud.astronomer.io and your desired Deployment
2. Create API keys
3. Save API keys as temp OS-level env vars
4. Run `astro context switch astronomer.io`
5. Run `astro deployment update --deployment-file my-file.yml`

**📸 Bug**

```
(venv) (base) magdagultekin@Magdalenas-MacBook-Pro astro-project % astro deployment update --deployment-file deployment-config.yml 
Using an Astro API key
Error: workspace_name: Onboarding - Customer Success does not exist in organization: cknaqyipv05731evsry6cj4n0
```

Config file:
```
deployment:
    configuration:
        name: magda-tmp
        description: ""
        runtime_version: 7.2.0
        dag_deploy_enabled: false
        scheduler_au: 0
        scheduler_count: 0
        cluster_name: CustomerSuccess
        workspace_name: Onboarding - Customer Success
    worker_queues:
        - name: default
          max_worker_count: 8
          min_worker_count: 1
          worker_concurrency: 16
          worker_type: e2-standard-4
```
