### ISSUE TITLE
CLI: Deployment Status not working with `astro deployment inspect`

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#1084]
**Describe the bug**

When you run `astro deployment inspect` the status shown for deployments is always "UNKOWN". This field should show the actual status of the deployment the same as the UI. This may be because changes to this feature were released recently

```
metadata:
        deployment_id: cle4p0fdt325082f05nco4rt6pu
        workspace_id: cl1vvhd0c85301fyobcagec1c
        cluster_id: cl3sm2lb500kh0synhlc7bh14
        release_name: prehistoric-solar-4891
        airflow_version: 2.5.1
        status: UNKNOWN
        created_at: 2023-02-14T20:24:33.761Z
        updated_at: 2023-02-14T20:24:33.761Z
```

**What CLI Version did you experience this bug?**

latest CLI version

**This CLI bug is related to which Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

**📸 Screenshots**
