### ISSUE TITLE
DEV: The status in the metadata section of deployment create command shown as "UNKNOWN"

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1102]
The deployment creation attempted through the yaml file generated the response data in which the status of the deployment says "UNKNOWN" instead of "CREATING"

deployment.yaml used is attached as deploy.txt.

Command used : 
```
astro deployment create --deployment-file deployment.yaml
```

Response is as follows:
```
deployment:
    environment_variables:
        - is_secret: false
          key: ENVIRONMENT
          updated_at: "2023-03-03T10:52:05.859Z"
          value: Dev
        - is_secret: false
          key: OPENLINEAGE_DISABLED
          updated_at: "2023-03-03T10:52:05.859Z"
          value: "true"
    configuration:
        name: performance_basic_deployment-94
        description: ""
        runtime_version: 7.3.0
        dag_deploy_enabled: false
        executor: CeleryExecutor
        scheduler_au: 5
        scheduler_count: 1
        cluster_name: DND_Perform-896
        workspace_name: QA Performance test workspace
    worker_queues:
        - name: default
          max_worker_count: 1
          min_worker_count: 0
          worker_concurrency: 16
          worker_type: e2-standard-4
    metadata:
        deployment_id: clesf0kvd1488503m1kcpa4tfg0
        workspace_id: clep7pkiu178851h21yn53pr8b
        cluster_id: cles7ks60001701l3b2ffcwuy
        release_name: desolate-exploration-4976
        airflow_version: 2.5.1
        current_tag: 7.3.0
        status: UNKNOWN
        created_at: 2023-03-03T10:51:12.936Z
        updated_at: 2023-03-03T10:52:05.874Z
        deployment_url: cloud.astronomer-dev.io/clep7pkiu178851h21yn53pr8b/deployments/clesf0kvd1488503m1kcpa4tfg0/analytics
        webserver_url: astronomer.astronomer-dev.run/dpa4tfg0
```

**What CLI Version did you experience this bug?**

1.11.0

**This CLI bug is related to which Astronomer Platform?**

Astro

**🪜 Steps To Reproduce**

1. Create deployment using the deployment configurations specified in the yaml file
2. Validate the deployment details generated at the metadata section of the response

[deploy.txt](https://github.com/astronomer/astro-cli/files/10881239/deploy.txt)
