### ISSUE TITLE
DEV- Namespace details available in CLI output under metadata

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1187]
In the deployment creation process through Cloud UI, the details such as namespace, clusters are hidden.
However while creating the deployment through CLI, the namespace details are seen under the meta data section of the CLI output

Meta data section of the deployment:
```
 metadata:
        deployment_id: clh9igt17066330yrdzxiedja
        workspace_id: clg3ajf1k003i01lr2cad687h
        cluster_id: N/A
        release_name: meteoroidal-lens-7447
        airflow_version: 2.6.0
        current_tag: 8.0.0
        status: UNKNOWN
        created_at: 2023-05-04T19:19:18.523Z
        updated_at: 2023-05-04T19:19:18.523Z
        deployment_url: cloud.astronomer-dev.io/clg3ajf1k003i01lr2cad687h/deployments/clh9igt17066330yrdzxiedja/analytics
        webserver_url: hosted-runtime-org-shri.astronomer-dev.run/dzxiedja
```

**What CLI Version did you experience this bug?**
SNAPSHOT-266b5f36

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro Hosted

**What Operating System is the above CLI installed on?**
Ventura 
13.3.1 (a) (22E772610a)

**🪜 Steps To Reproduce**

1.Create a Standard hosted deployment through CLI and observe the meta data section.

Expected:
Namespace should not be mentioned

Actual:
Namespace details are seen.
