### ISSUE TITLE
DEV-Standard deployment creation using deployment file looks for cluster name input

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1199]
In standard cluster since the user would not be aware of the cluster name to which the deployment would get tagged, while creating deployment using deployment file, the file would have all details except for the cluster name.
However, if we give a deployment file and try to create a deployment with following commands, the error as shown in the code block is seen.

Also , with the existing template to create the deployment, user would need to specify the Astro machine specification in worker-queues section and would not be able to use the astro machines by specifying A5,A10 or A20 machine 

```
shrividyahegde@10 test_dep % ./astro deployment create --deployment-file sample.yaml
Error: missing required field: deployment.configuration.cluster_name                                                                       
shrividyahegde@10 test_dep % cat sample.yaml 
deployment:
    configuration:
        name: test
        description: ""
        runtime_version: 8.1.0
        dag_deploy_enabled: false
        executor: CeleryExecutor
        scheduler_au: 10
        scheduler_count: 2
        cloud_provider : gcp
        region: us-central1
    worker_queues:
        - name: default
          max_worker_count: 10
          min_worker_count: 0
          worker_concurrency: 5
```

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**Comment by shri-astro** [comment]
```
shrividyahegde@Shrividyas-MacBook-Pro Documents % astro deployment create --deployment-file sample.yaml
deployment:
    configuration:
        name: gcp_test_standard_through_inspect
        description: ""
        runtime_version: 8.4.0
        dag_deploy_enabled: false
        ci_cd_enforcement: false
        scheduler_size: small
        is_high_availability: false
        executor: CeleryExecutor
        scheduler_au: 10
        scheduler_count: 1
        cluster_name: us-central1
        workspace_name: Test Automated Workspace
        deployment_type: HOSTED_SHARED
        cloud_provider: gcp
        region: us-central1
    worker_queues:
        - name: default
          max_worker_count: 4
          min_worker_count: 3
          worker_concurrency: 20
          worker_type: a20
    metadata:
        deployment_id: clix47lns235701iz1ddgrjtka
        workspace_id: clix0m97m001i01oiqr98vqb5
        cluster_id: us-central1
        release_name: N/A
        airflow_version: 2.6.1
        current_tag: 8.4.0
        status: UNKNOWN
        created_at: 2023-06-15T12:26:24.999Z
        updated_at: 2023-06-15T12:26:24.999Z
        deployment_url: cloud.astronomer-dev.io/clix0m97m001i01oiqr98vqb5/deployments/clix47lns235701iz1ddgrjtka/analytics
        webserver_url: org-shri-hosted-dedicated-1.astronomer-dev.run/ddgrjtka
        workload_identity: astro-ultraviolet-ionosphere-7@astro-gcp-data-plane-dev.iam.gserviceaccount.com

shrividyahegde@Shrividyas-MacBook-Pro Documents % cat sample.yaml 
deployment:
    configuration:
        name: gcp_test_standard_through_inspect
        description: ""
        runtime_version: 8.4.0
        dag_deploy_enabled: false
        ci_cd_enforcement: false
        scheduler_size: small
        is_high_availability: false
        executor: CeleryExecutor
        scheduler_au: 10
        scheduler_count: 1
        workspace_name: Test Automated Workspace
        deployment_type: HOSTED_SHARED
        cloud_provider: gcp
        region: us-central1
        cluster_name: us-central1
    worker_queues:
        - name: default
          max_worker_count: 4
          min_worker_count: 3
          worker_concurrency: 20
          worker_type: a20
          ```
          
          Retested and resolved.
