### ISSUE TITLE
DEV-deployment inspect displays the cluster name for the given deployment for Standard ones

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1222]
On inspecting a standard deployment, the cluster name of the deployment is displayed.
Unless this is expected, we should probably have this value masked so that the user won't be able to see the cluster name on inspect just like how the user is not able to access the cluster name from the UI

Response attached

```
deployment:
    environment_variables:
        - is_secret: false
          key: AIRFLOW_CONN_KUBERNETES_DEFAULT
          updated_at: "2023-05-21T10:31:13.495Z"
          value: kubernetes://
    configuration:
        name: KE
        description: ""
        runtime_version: 8.2.0
        dag_deploy_enabled: false
        executor: KubernetesExecutor
        scheduler_au: 10
        scheduler_count: 1
        cluster_name: Shared GCP us-central1
        workspace_name: Shri workspace
    worker_queues:
        - name: default
          worker_type: ""
          pod_cpu: "0.25"
          pod_ram: 0.48828125Gi
    metadata:
        deployment_id: clhxa02tf805633lxgisezvuyz
        workspace_id: clhq3pg69002k01obsw7o9oxv
        cluster_id: clgl8omhr000o01mbfgpng61v
        release_name: popular-meteor-7495
        airflow_version: 2.6.1
        current_tag: 8.2.0
        status: UNKNOWN
        created_at: 2023-05-21T10:28:49.347Z
        updated_at: 2023-05-21T10:31:13.51Z
        deployment_url: cloud.astronomer-dev.io/clhq3pg69002k01obsw7o9oxv/deployments/clhxa02tf805633lxgisezvuyz/analytics
        webserver_url: org-shri-hosted-org.astronomer-dev.run/dsezvuyz
```

**What CLI Version did you experience this bug?**
1.15.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**
```
shrividyahegde@Shrividyas-MacBook-Pro test_dep % astro deployment inspect
Select a Deployment
 #     DEPLOYMENT NAME     RELEASE NAME            DEPLOYMENT ID                  
 1     CE                  modern-fission-7751     clhx9z4j2803073lxgp8c9h851     
 2     KE                  popular-meteor-7495     clhxa02tf805633lxgisezvuyz     

> 2
deployment:
    environment_variables:
        - is_secret: false
          key: AIRFLOW_CONN_KUBERNETES_DEFAULT
          updated_at: "2023-05-21T10:31:13.495Z"
          value: kubernetes://
    configuration:
        name: KE
        description: ""
        runtime_version: 8.2.0
        dag_deploy_enabled: false
        executor: KubernetesExecutor
        scheduler_au: 10
        scheduler_count: 1
        cluster_name: Shared GCP us-central1
        workspace_name: Shri workspace
    worker_queues:
        - name: default
          worker_type: ""
          pod_cpu: "0.25"
          pod_ram: 0.48828125Gi
    metadata:
        deployment_id: clhxa02tf805633lxgisezvuyz
        workspace_id: clhq3pg69002k01obsw7o9oxv
        cluster_id: clgl8omhr000o01mbfgpng61v
        release_name: popular-meteor-7495
        airflow_version: 2.6.1
        current_tag: 8.2.0
        status: UNKNOWN
        created_at: 2023-05-21T10:28:49.347Z
        updated_at: 2023-05-21T10:31:13.51Z
        deployment_url: cloud.astronomer-dev.io/clhq3pg69002k01obsw7o9oxv/deployments/clhxa02tf805633lxgisezvuyz/analytics
        webserver_url: org-shri-hosted-org.astronomer-dev.run/dsezvuyz
```
