### ISSUE TITLE
Managing Deployments as code doesn't work as expected on Astro hosted

### ISSUE THREAD

**Issue by jwitz** [astronomer/astro-cli#1231]
**Describe the bug**

As a Hosted user, I expect `astro deployment inspect` and `astro deployment update` to work with with template files on Astro Hosted. I encountered two bugs that make the feature not work:

- The worker type (A5/10/20) was not properly inspected on the Deployment. I only got a blank value for `worker_type`:

    ```yaml
    worker_queues:
        - name: default
          max_worker_count: 2
          min_worker_count: 0
          worker_concurrency: 5
          worker_type: ""
    ```
- When I reapplied my config to the Deployment, the CLI didn't recognize the cluster that it had just inspected:

    ```
    jacobwitz@Jacobs-MacBook-Pro documents % astro deployment update "jake test" --deployment-file template.yaml 
    Error: cluster_name: Shared GCP us-central1 does not exist in organization: cli0loudl001b01nlk92wy43v
    jacobwitz@Jacobs-MacBook-Pro documents % 
    ```

**What CLI Version did you experience this bug?**

1.15.1

**This CLI bug is related to which Astronomer Platform?**

- [X] Astro
- [ ] Software
- [ ] None/Unknown

MacOS Ventura 13.2.1

**🪜 Steps To Reproduce**

```sh
astro deployment inspect -n "deployment name" > template.yaml

astro deployment update "deployment name" --deployment-file template.yaml
```
