### ISSUE TITLE
DEV- Template file creation for deployment inspect is erroring out

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1343]
A deployment was created and the template file creation was attempted using the following commands available in Astro CLI documentation.
The deployment exists in the given workspace still the error indicated that the deployment doesn't exist in the workspace.

```
# save the template to a YAML file
astro deployment inspect <deployment-name>  --template  > <deployment-template-file-name>
# save the template to a JSON file
astro deployment inspect <deployment-name>  --template --output json > <deployment-template-file-name>
# print the template to your terminal
astro deployment inspect <deployment-name>  --template
```

Actual results:

```
shrividyahegde@Shrividyas-MacBook-Pro Documents % astro deployment inspect "Test_deployment_template" --template 
Error: the Deployment specified was not found in this workspace. Your account or API Key may not have access to the deployment specified
shrividyahegde@Shrividyas-MacBook-Pro Documents % astro workspace list
Using an Astro API Token
 NAME                                                 ID                            
 Astro_hosted_CLI_Automation_Restricted_Workspace     clkmpjzfk002d01m8vnpg1tu7     
 Test Automated Workspace                             clix0m97m001i01oiqr98vqb5     
shrividyahegde@Shrividyas-MacBook-Pro Documents % astro deployment list
Using an Astro API Token
 NAME                         NAMESPACE     CLUSTER      DEPLOYMENT ID                 RUNTIME VERSION                    DAG DEPLOY ENABLED     CI-CD ENFORCEMENT     
 Test_deployment_template     N/A           us-east4     cll0rt19y23921bvf0qdhhza0     8.8.0 (based on Airflow 2.6.3)     false                  false                 
shrividyahegde@Shrividyas-MacBook-Pro Documents % astro deployment inspect Test_deployment_template --template  > deployment-template-file-name.yaml 
Error: the Deployment specified was not found in this workspace. Your account or API Key may not have access to the deployment specified
shrividyahegde@Shrividyas-MacBook-Pro Documents % astro deployment inspect "Test_deployment_template"  --template --output json > deployment-template-file-name.json
Error: the Deployment specified was not found in this workspace. Your account or API Key may not have access to the deployment specified
shrividyahegde@Shrividyas-MacBook-Pro Documents % astro deployment inspect "Test_deployment_template" --template
Error: the Deployment specified was not found in this workspace. Your account or API Key may not have access to the deployment specified
shrividyahegde@Shrividyas-MacBook-Pro Documents % 
```

When the same operation was tried without mentioning the name of the deployment, the inspect template was generated:
```
shrividyahegde@Shrividyas-MacBook-Pro Documents % astro deployment inspect  --template 

Only one Deployment was found. Using the following Deployment by default: 

 Deployment Name: Test_deployment_template
 Deployment ID: cll0rt19y23921bvf0qdhhza0

deployment:
    configuration:
        name: ""
        description: ""
        runtime_version: 8.8.0
        dag_deploy_enabled: false
        ci_cd_enforcement: false
        scheduler_size: small
        is_high_availability: false
        executor: CeleryExecutor
        scheduler_au: 10
        scheduler_count: 1
        cluster_name: us-east4
        workspace_name: Astro_hosted_CLI_Automation_Restricted_Workspace
        deployment_type: HOSTED_SHARED
        cloud_provider: gcp
        region: us-east4
    worker_queues:
        - name: default
          max_worker_count: 10
          min_worker_count: 0
          worker_concurrency: 5
          worker_type: a5
```
**What CLI Version did you experience this bug?**
1.18.1

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro

**Comment by shri-astro** [comment]
Going by the help text, this error was seen, 
On specifying -n with the flag, seems like the command is generating the  template as expected:
```
shrividyahegde@Hegde testlimits % astro deployment inspect -n "t1" --template > deployment-template-file-name.yaml 
shrividyahegde@Hegde testlimits % cat deployment-template-file-name.yaml 
deployment:
    configuration:
        name: ""
        description: ""
        runtime_version: 9.6.0
        dag_deploy_enabled: true
        ci_cd_enforcement: false
        scheduler_size: small
        is_high_availability: false
        executor: CeleryExecutor
        scheduler_au: 10
        scheduler_count: 1
        cluster_name: us-east4
        workspace_name: Test Automation Workspace
        deployment_type: HOSTED_SHARED
        cloud_provider: gcp
        region: us-east4
    worker_queues:
        - name: default
          max_worker_count: 10
          min_worker_count: 0
          worker_concurrency: 5
          worker_type: a5

shrividyahegde@Hegde testlimits % astro deployment list
 NAME     NAMESPACE     CLUSTER      DEPLOYMENT ID                 RUNTIME VERSION                    DAG DEPLOY ENABLED     CI-CD ENFORCEMENT     
 t1       N/A           us-east4     clq0wa4q124031uyqx4cdddn0     9.6.0 (based on Airflow 2.7.3)     true                   false                 
 name     N/A           us-east4     clq0vx7ey05171u1x2cdhja4d     9.6.0 (based on Airflow 2.7.3)     true                   false                 
shrividyahegde@Hegde testlimits % 

```

leaving the ticket open for further triage
cc: @kushalmalani
