### ISSUE TITLE
DEV-Deployment creation using yaml files errors due to irrelevant worker type in KE

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1357]
As a user on creating the deployment using deployment file using the below files.
Celery deployment was created without any issue but KE deployment gave the below error:
```
Error: KubernetesExecutor does not support pod cpu in the request. It will be calculated based on the requested worker type
```

considering there is no worker type support for KE and that KE works with a5 configuration under the hood, is this an expected change?

KE file:
```
    deployment:
        configuration:
            name: cli_auto_gcp_standard_dagdeploy_enable_KubernetesExecutor_HA_disabled_small_cicdflag_False_8.8.0_2023-08-16 20:35:19.328852
            description: ""
            runtime_version: 8.8.0
            dag_deploy_enabled: true
            ci_cd_enforcement: false
            scheduler_size: small
            is_high_availability: false
            executor: KubernetesExecutor
            scheduler_au: 10
            scheduler_count: 1
            cluster_name: us-east4
            workspace_name: Astro_hosted_CLI_Automation_Restricted_Workspace
            deployment_type: HOSTED_SHARED
            cloud_provider: gcp
            region: us-east4
        worker_queues:
            - name: default
              pod_cpu: "0.25"
              pod_ram: 0.5Gi
              worker_type: a5
```

CE file:
```
    deployment:
        configuration:
            name: cli_auto_gcp_standard_dagdeploy_enable_CeleryExecutor_HA_disabled_small_cicdflag_False_8.8.0_2023-08-16 20:36:20.638550
            description: ""
            runtime_version: 8.8.0
            dag_deploy_enabled: true
            ci_cd_enforcement: false
            scheduler_size: small
            is_high_availability: false
            executor: CeleryExecutor
            scheduler_au: 10
            scheduler_count: 1
            cluster_name: us-east4
            workspace_name: Astro_hosted_CLI_Automation_Restricted_Workspace
            deployment_type: HOSTED_SHARED
            cloud_provider: gcp
            region: us-east4
        worker_queues:
            - name: default
              max_worker_count: 10
              min_worker_count: 0
              worker_type: a5
              worker_concurrency: 5
 ```

**What CLI Version did you experience this bug?**
1.18.2

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro

**Comment by sunkickr** [comment]
Users having similar issues on hybrid. User is  getting the error:
```
Error: KubernetesExecutor does not support minimum worker count in the request. It can only be used with CeleryExecutor
```
When they are trying to create a kubernetes deployment with a worker type which can be done in the UI

**Comment by shri-astro** [comment]
Latest observation:
```
shrividyahegde@Hegde testlimits % astro deployment create --deployment-file dep.yaml 
Error: workspace_name: Astro_hosted_CLI_Automation_Restricted_Workspace does not exist in organization: cls8jv7rv005n01nwea4m87p5
Usage:
  astro deployment create [flags]

Aliases:
  create, cr

Flags:
      --cicd-enforcement string          When enabled CI/CD Enforcement where deploys to deployment must use an API Key or Token. This essentially forces Deploys to happen through CI/CD. Possible values disable/enable
      --clean-output                     clean output to only include inspect yaml or json file in any situation.
  -p, --cloud-provider string            The Cloud Provider to use for the Deployment. Possible values can be gcp, aws. (default "gcp")
  -c, --cluster-id string                Cluster to create the Deployment in
      --dag-deploy string                Enables DAG-only deploys for the Deployment
      --default-task-pod-cpu string      The default task pod CPU to use for the Deployment. Example value: 0.25
      --default-task-pod-memory string   The default task pod memory to use for the Deployment. Example value: 0.5Gi
      --deployment-file string           Location of file containing the Deployment to create. File can be in either JSON or YAML format.
  -d, --description string               Description of the Deployment. If the description contains a space, specify the entire description in quotes ""
  -e, --executor string                  The executor to use for the Deployment. Possible values can be CeleryExecutor or KubernetesExecutor. (default "CeleryExecutor")
  -h, --help                             help for create
  -a, --high-availability string         Enables High Availability for the Deployment (default "disable")
  -n, --name string                      The Deployment's name. If the name contains a space, specify the entire name within quotes "" 
      --region string                    The Cloud Provider region to use for the Deployment.
      --resource-quota-cpu string        The Deployment's CPU resource quota. Example value: 10
      --resource-quota-memory string     The Deployment's memory resource quota. Example value: 20Gi
  -v, --runtime-version string           Runtime version for the Deployment
      --scheduler-size string            The size of scheduler for the Deployment. Possible values can be small, medium, large
      --type string                      The Type to use for the Deployment. Possible values can be standard or dedicated. (default "standard")
  -i, --wait                             Wait for the Deployment to become healthy before ending the command
  -w, --workspace-id string              Workspace to create the Deployment in

Global Flags:
      --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "warning")


```

**Comment by shri-astro** [comment]
Resolved:
```
shrividyahegde@Hegde testlimits % astro deployment create --deployment-file dep.yaml 
deployment:
    configuration:
        name: cli_auto_gcp_standard_dagdeploy_enable_KubernetesExecutor_HA_disabled_small_cicdflag_False_8.8.0_2023-08-16 20:35:19.328852
        description: ""
        runtime_version: 8.8.0
        dag_deploy_enabled: true
        ci_cd_enforcement: false
        scheduler_size: SMALL
        is_high_availability: false
        executor: KUBERNETES
        scheduler_count: 1
        workspace_name: Automation API dev workspace
        deployment_type: STANDARD
        cloud_provider: GCP
        region: us-east4
        default_task_pod_cpu: "0.25"
        default_task_pod_memory: 0.5Gi
        resource_quota_cpu: "10"
        resource_quota_memory: 20Gi
    worker_queues: []
    metadata:
        deployment_id: clt2pjub409uc01qjg35kippz
        workspace_id: cls8pqheo00i301pcq8x7bi1z
        cluster_id: N/A
        release_name: N/A
        airflow_version: 2.6.3
        current_tag: 8.8.0
        status: CREATING
        created_at: 2024-02-26T08:59:42.445Z
        updated_at: 2024-02-26T08:59:42.445Z
        deployment_url: cloud.astronomer-dev.io/cls8pqheo00i301pcq8x7bi1z/deployments/clt2pjub409uc01qjg35kippz/overview
        webserver_url: cls8jv7rv005n01nwea4m87p5.astronomer-dev.run/d35kippz?orgId=org_9zXCd6J5uyO30beS
        workload_identity: astro-accurate-gravitation-487@astro-dev-us-east4-0001.iam.gserviceaccount.com
        ```
