### ISSUE TITLE
DEV- Inspect command doesn't display the name of the deployment when --template is used

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1393]
**Describe the bug**

To inspect a particular deployment if I use the command ```astro deployment inspect -n <name of the deployment>``` , then the output yaml will contain the name of the deployment but when the same is tried using ```astro deployment inspect -n <name of the deployment> --template```, then the name of the deployment is not being displayed.
Output mentioned for the same.

```
shrividyahegde@Shrividyas-MacBook-Pro ~ % astro deployment inspect -n "cli_auto_gcp_dedicated_dagdeploy_disable_KubernetesExecutor_HA_disabled_small_scheduler_cicdflag_False_9.1.0_2023-09-20 14:19:10.053951"
deployment:
    configuration:
        name: cli_auto_gcp_dedicated_dagdeploy_disable_KubernetesExecutor_HA_disabled_small_scheduler_cicdflag_False_9.1.0_2023-09-20 14:19:10.053951
        description: ""
        runtime_version: 9.1.0
        dag_deploy_enabled: false
        ci_cd_enforcement: false
        scheduler_size: small
        is_high_availability: false
        executor: KubernetesExecutor
        scheduler_au: 10
        scheduler_count: 1
        cluster_name: Dedicated cluster for deployment testing13:37:30.085083
        workspace_name: Astro_hosted_CLI_Automation_Restricted_Workspace
        deployment_type: HOSTED_DEDICATED
        cloud_provider: gcp
        region: us-central1
    worker_queues:
        - name: default
          worker_type: a5
          pod_cpu: "0.25"
          pod_ram: 0.5Gi
    metadata:
        deployment_id: clmri5yn06745871u1mz5s9ptxf
        workspace_id: clkmpjzfk002d01m8vnpg1tu7
        cluster_id: clmolsm2o00nx01dum2vwupn5
        release_name: N/A
        airflow_version: 2.7.1
        current_tag: 9.1.0
        status: HEALTHY
        created_at: 2023-09-20T08:49:15.42Z
        updated_at: 2023-09-20T08:49:15.419Z
        deployment_url: cloud.astronomer-dev.io/clkmpjzfk002d01m8vnpg1tu7/deployments/clmri5yn06745871u1mz5s9ptxf/overview
        webserver_url: org-shri-hosted-dedicated-1.astronomer-dev.run/d5s9ptxf
        workload_identity: astro-asteroidal-blueshift-881@hcdp-clmolsm2o00nx01dum2vwupn5.iam.gserviceaccount.com

```

```
shrividyahegde@Shrividyas-MacBook-Pro ~ % astro deployment inspect -n "cli_auto_gcp_dedicated_dagdeploy_disable_KubernetesExecutor_HA_disabled_small_scheduler_cicdflag_False_9.1.0_2023-09-20 14:53:59.070762" --template
deployment:
    configuration:
        name: ""
        description: ""
        runtime_version: 9.1.0
        dag_deploy_enabled: false
        ci_cd_enforcement: false
        scheduler_size: small
        is_high_availability: false
        executor: KubernetesExecutor
        scheduler_au: 10
        scheduler_count: 1
        cluster_name: Dedicated cluster for deployment testing13:37:30.085083
        workspace_name: Astro_hosted_CLI_Automation_Restricted_Workspace
        deployment_type: HOSTED_DEDICATED
        cloud_provider: gcp
        region: us-central1
    worker_queues:
        - name: default
          worker_type: a5
          pod_cpu: "0.25"
          pod_ram: 0.5Gi
```
**What CLI Version did you experience this bug?**
1.19.2

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro
