### ISSUE TITLE
Internal server error when running `astro deploy` on Astro CLI v1.20.0

### ISSUE THREAD

**Issue by szeswee** [astronomer/astro-cli#1437]
**Describe the bug**

On version v1.20.0 of the Astro CLI, we are encountering an issue with deployment to an Astro Hybrid workspace on Github Actions with an unpinned Astro CLI version. Pinning the version to v1.19.4 fixes the issue and we are able to deploy successfully.

Console output is as follow:
```
...
#11 DONE 6.6s
#12 exporting to image
#12 exporting layers
#12 exporting layers 8.0s done
#12 writing image sha256:a1be0689b4d3bff61d6f8bab1a6fb3376d2c6c74cc959c615d0043f456dc512b done
#12 naming to docker.io/xxxxx/airflow:latest done
#12 DONE 8.0s
WARNING! You are currently running Astro Runtime Version 9.4.0
Consider upgrading to the latest version, Astro Runtime 9.5.0
testing xxxxx/airflow:latest
Pushing image to Astronomer registry
The push refers to repository [images.astronomer.cloud/xxxxxx/xxxxxx]
3083c78e1544: Pushed
0db692010687: Pushed
956650e352a8: Pushed
f7ec3070ed1a: Pushed
5f70bf18a086: Pushed
0a8aed4ff1f9: Pushed
a7ade263121d: Pushed
d611b5a00096: Pushed
1f199c95f92c: Pushed
45e5aec13126: Pushed
bae7a5b05029: Pushed
552ada5e939b: Pushed
5e64823bbe35: Pushed
257f3eae02b7: Pushed
1553c95ed935: Pushed
1894aa8b998c: Pushed
7eeef09a7852: Pushed
6fd1c8ff41e8: Pushed
691dc47a23cd: Pushed
bba0db24dbf9: Pushed
2af7ca654757: Pushed
849102502afc: Pushed
c2989d4a849f: Pushed
aceb7221cfb3: Pushed
873dd994182b: Pushed
307827328e83: Pushed
1343d377f1a7: Pushed
c1f03545c72b: Pushed
14d81996f1a9: Pushed
17bed8cbce0e: Pushed
52d192a50c78: Pushed
6c2e00f5e765: Pushed
1e64efec925f: Pushed
82e0c38f9eb9: Pushed
c16ef7e693ab: Pushed
633f5bf471f7: Pushed
4b9743b43984: Pushed
deploy-2023-11-08T06-00-01: digest: sha256:67e923c6c928ae8cb97a0795f687444fd57ca412b48c27410fe71013e45244fe size: 8054
Error: Invalid request: Could not get docker registry token for request: Internal server error
```

**What CLI Version did you experience this bug?**

v1.20.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro
- [x] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

Ubuntu 22.04 on Github Actions

**🪜 Steps To Reproduce**

1. Trigger a Github Actions workflow run with the following YML for an Astro Hybrid project (replace `ASTRO_API_TOKEN` and `ASTRO_DEPLOYMENT_NAME` env values with your own):
    ```yml
    name: Deploy

    env:
      ASTRO_API_TOKEN: super_secret_token
      ASTRO_DEPLOYMENT_NAME: my_deployment

    jobs:
      deploy-to-astronomer:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository code
            uses: actions/checkout@v3

          - name: Install Astro CLI
            run: |
              curl -sSL install.astronomer.io | sudo bash -s

          - name: Deploy Airflow code on Astronomer
            run: |
              astro deploy --force --deployment-name=${{ env.ASTRO_DEPLOYMENT_NAME }}
    ```
