### ISSUE TITLE
DEV - Region field is not displayed for dedicated cluster based deployment on inspecting 

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1511]
The deployment created under the dedicated cluster was inspected using the astro deployment inspect command.
The following response was seen
The region field seems to be missing here
```

shrividyahegde@Hegde ~ % astro deployment inspect
Only one Deployment was found. Using the following Deployment by default: 

 Deployment Name: test
 Deployment ID: cls1px8xj03bq01llrzizg9nr

deployment:
    configuration:
        name: test
        description: ""
        runtime_version: 10.2.0
        dag_deploy_enabled: false
        ci_cd_enforcement: false
        scheduler_size: SMALL
        is_high_availability: false
        executor: CELERY
        scheduler_au: 0
        scheduler_count: 1
        cluster_name: Dedicated cluster for testing13:55:52.157504
        workspace_name: Astro_hosted_CLI_Automation_Restricted_Workspace
        deployment_type: DEDICATED
        cloud_provider: gcp
        region: ""
        default_task_pod_cpu: "0.25"
        default_task_pod_memory: 0.5Gi
        resource_quota_cpu: "10"
        resource_quota_memory: 20Gi
    worker_queues:
        - name: default
          max_worker_count: 10
          worker_concurrency: 5
          worker_type: A5
    metadata:
        deployment_id: cls1px8xj03bq01llrzizg9nr
        workspace_id: clkmpjzfk002d01m8vnpg1tu7
        cluster_id: cls1iwbsy018701llw7bjneov
        release_name: N/A
        airflow_version: 2.8.1
        current_tag: 10.2.0
        status: HEALTHY
        created_at: 2024-01-31T11:42:39.384Z
        updated_at: 2024-01-31T11:58:31.631Z
        deployment_url: cloud.astronomer-dev.io/clkmpjzfk002d01m8vnpg1tu7/deployments/cls1px8xj03bq01llrzizg9nr/overview
        webserver_url: org-shri-hosted-dedicated-1.astronomer-dev.run/dzizg9nr?orgId=org_tYq2jzuSrYWdJjrZ
        workload_identity: astro-galactian-radiation-1295@hcdp-cls1iwbsy018701llw7bjneov.iam.gserviceaccount.com
    alert_emails:
        - shrividya.hegde@astronomer.io
```

**What CLI Version did you experience this bug?**
2.0.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro
