### ISSUE TITLE
`astro dev object import` ignores `conn_extras` field

### ISSUE THREAD

**Issue by zach-nicoll-wcq** [astronomer/astro-cli#1591]
**Describe the bug**

Our `airflow_settings.yaml` file contains connections that make use of the `conn_extra` field (we are using the `aws` connection type).

However, when attempting to import these values into the UI via `astro dev object import`, the `conn_extra` field is ignored and the key/value pairs are not uploaded.

The terminal output makes no indication that something has gone wrong:

```sh
astro dev object import
Updating Connection "athena-transformed-dev"...
Added Connection: athena-transformed-dev
Updating Connection "athena-trusted-dev"...
Added Connection: athena-trusted-dev
```

**What CLI Version did you experience this bug?**

1.24.1

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

- MacOS
- Nobara (Fedora) Linux

**🪜 Steps To Reproduce**

1. Create an `airflow_settings.yaml` file that looks like this:

```yaml
airflow:
  connections:
  - conn_extra:
      aws_session_token: some_token
      role_arn: some_role
    conn_id: conn_1
    conn_login: some_login
    conn_password: some_password
    conn_type: aws
  - conn_extra:
      aws_session_token: some_token
      role_arn: some_role
    conn_id: conn_1
    conn_login: some_login
    conn_password: some_password
    conn_type: aws
```
2. Run `astro dev object import`
3. Observe the 'Extra' field to be an empty JSON object

**📸 Screenshots**

![image](https://github.com/astronomer/astro-cli/assets/151692348/71959023-2239-4ffd-b3ad-717131beafa0)
