### ISSUE TITLE
Set up connections by default with `astro airflow init`

### ISSUE THREAD

**Issue by benjamingregory** [astronomer/astro-cli#160]
Request by @Tristan-Soriano: 

I want a way to set up all my dev connection without dealing with it in the UI or having extra script to run once "astro airflow start" is done

**Comment by benjamingregory** [comment]
Proposed YAML structure
```
airflow:
  connections:
      - conn_id: my_s3
        conn_type: s3
        conn_extra: {"key":"XXX", "secret": "XXX"}
      - conn_id: my_postgres
        conn_type: Postgres
        conn_host: 12.2.2.1
        conn_login: user
        conn_password: password
        conn_port: 5342
  pools:
      - pool_name: my_new_pool
        pool_slot: 4
        pool_description: for_the_haters
  variables:
      - variable_name: new_variable
        variable_value: {"Never Gonna": "Give You Up"}
      - variable_name: second_variable
        variable_value: {"Never Gonna": "Let You Down"}
```
