### ISSUE TITLE
Deployment created with workload identity in yaml does not work

### ISSUE THREAD

**Issue by stuart23** [astronomer/astro-cli#1699]
**Describe the bug**

When creating a deployment with the following config, the specified workload identity is not applied to the deployment. See [here](https://management.astronomer.cloud/deployments/clilt7rt8009l01i7wf7xnz94/clzls46zh08h501n93nqim5g1/details) for the created deployment (screenshot below)

```
deployment:
    environment_variables:
        - is_secret: false
          key: PROJECT_NAME
          updated_at: "2023-06-22T14:02:26.281Z"
          value: test_project
        - is_secret: true
          key: API_KEY
          updated_at: "2023-06-22T14:02:27.892Z"
          value: ""
    configuration:
        name: test-standard
        description: ""
        runtime_version: 10.3.0
        dag_deploy_enabled: true
        ci_cd_enforcement: false
        scheduler_size: SMALL
        is_high_availability: false
        executor: CELERY
        workspace_name: "CRE Sandbox Hosted"
        deployment_type: STANDARD
        cloud_provider: aws
        cluster_name: "cluhqac4x04um01lo0ny85fbo" ## Only used when deployment_type is DEDICATED
        region: us-east-1
        default_task_pod_cpu: "0.25"
        default_task_pod_memory: 0.5Gi
        resource_quota_cpu: "10"
        resource_quota_memory: 20Gi
        is_development_mode: true
        hibernation_schedules:
          - hibernate_at: "1 * * * * "
            wake_at: "2 * * * *"
            description: "My hibernation description"
            enabled: true
        workload_identity: arn:aws:iam::clskz0os1000308jz2prn0s8u:role/clskyy4h8000208jz60olha0w-release
    worker_queues: ## worker_queues only used when executor is CELERY
      - name: default
        max_worker_count: 10
        min_worker_count: 0
        worker_concurrency: 5
        worker_type: A5
    alert_emails:
        - test-emailclskz4wu5000508jz4gm25q5j@testdomain.io
```

![image](https://github.com/user-attachments/assets/e9cb1482-fac8-4b1e-9c60-c8afcc15833f)

**What CLI Version did you experience this bug?**

Astro CLI Version: 1.27.1 but customer reported it with GH action v0.6
![image](https://github.com/user-attachments/assets/4d1f4631-dd11-41f7-a75d-226f86c77519)

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

OSX

**🪜 Steps To Reproduce**

```
astro deployment create --deployment-file  deployment.yaml
```

**📸 Screenshots**
