### ISSUE TITLE
conn_extra parameter is not preserving case for json keys

### ISSUE THREAD

**Issue by sakethsomaraju** [astronomer/astro-cli#1737]
1. When running airflow locally with `astro dev start` and configuring connections with `airflow_settings.yaml`, astro cli do not preserve case for keys in conn_extra argument.

```yaml
airflow:
  connections:
    - conn_id: test12
      conn_type: generic
      conn_host:
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
        example_extra_field: example-value
        testVarCASE: UPPERCASE123
```

Here testVarCASE is getting converted into testvarcase

**What CLI Version did you experience this bug?**

1.30.0

**What Operating System is the above CLI installed on?**

MAC

**🪜 Steps To Reproduce**

1. `astro dev init` to create a new local project
2. update `airflow_settings.yaml` to add the above connection.
3. Run `astro dev start` and check connection with `airflow connections get test12`

**📸 Screenshots**

![Image](https://github.com/user-attachments/assets/1f23365b-c5e2-4824-be06-2e9e81f99329)
