### ISSUE TITLE
Unable to deploy dags to Stage Env through Github Action

### ISSUE THREAD

**Issue by dsgupta02** [astronomer/astro-cli#754]
**We are not able to set context to stage or dev environment.**

```
Error: not connected, have you authenticated to Astro? Run astro login and try again
```

**What CLI Version did you experience this bug?**
Astro CLI Version: `1.5.1`
Tried in `1.5.0` and `1.3.0` too

**🪜 Steps To Reproduce**
1. Set  the following as github sercet
    ASTRONOMER_KEY_ID
    ASTRONOMER_KEY_SECRET
2. Create a new YAML file in `.github/workflows` that includes the following configuration.
3. Added astro project in same branch

**YAML file** 
```
name: Astronomer CI - Deploy code

on:
  push:
    branches:
      - dag_deployment

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
  ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        curl -sSL install.astronomer.io | sudo bash -s
        astro deploy

```
**Output : ** 
<img width="1089" alt="Screenshot 2022-09-23 at 11 29 29 PM" src="https://user-images.githubusercontent.com/100349882/192036108-43766a5e-f331-48b9-b0c0-8848e13c85cd.png">

**Another try ->**
```
name: Astronomer CI - Deploy code

on:
  push:
    branches:
      - dag_deployment

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
  ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        curl -sSL https://install.astronomer.io | sudo bash -s -- v1.3.0
        astro context switch astronomer-stage.io
        cd dag_deployment
        astro deploy
```
**Output :**
<img width="1102" alt="Screenshot 2022-09-24 at 12 09 41 AM" src="https://user-images.githubusercontent.com/100349882/192035190-a7c2fecd-1abd-4bc6-a5c3-f0f8beb97d08.png">
