### ISSUE TITLE
Changes to`astro deployment inspect`

### ISSUE THREAD

**Issue by sunkickr** [astronomer/astro-cli#876]
- Change  `astronomer_variables` field to `environment_variables`
- rename `scheduler_replicas` to `scheduler_count`
- change `information` to `metadata`
- add `dag_deploy_enabled` (true or false) field to the metadata field
- Update Order of YAML produced by `astro deployment inspect`

`astro deployment inspect` currently creates a yaml representation of a Deployment this representation is currently in alphabetical order. It should be in the specific order shown below:

```
deployment:
    environment_variables:
        - is_secret: true
          key: AWS_ACCESS_KEY_ID
          updated_at: "2022-09-26T13:57:36.564Z"
          value:
    configuration:
        name: CE Prod
        description: ""
        runtime_version: 6.0.2
        scheduler_au: 20
        scheduler_count: 2
        cluster_id: cl66604ph00tx0s2tb3v313qu
    worker_queues:
        - name: heavy-compute
          id: cl8oigdwh135879hfw37mu9qrev
          is_default: false
          max_worker_count: 10
          min_worker_count: 0
          worker_concurrency: 4
          node_pool_id: cl8c3xz901505872c1d498z2zt9
       - name: default
          id: cl6l2mhvq280121b01r5mkcj05
          is_default: true
          max_worker_count: 10
          min_worker_count: 1
          worker_concurrency: 16
          node_pool_id: cl66604pi447851h2tpkvtlkrt
    metadata:
        deployment_id: cl6l2mhvq280081b01cg9g9nzw
        workspace_id: cl1ntvrrk411461gxsvvitduiy
        cluster_id: cl66604ph00tx0s2tb3v313qu
        release_name: blazing-opposition-4105
        airflow_version: 2.4.1
        status: HEALTHY
        created_at: 2022-08-08T18:12:18.566Z
        updated_at: 2022-11-14T23:38:06.649Z
        deployment_url: cloud.astronomer.io/cl1ntvrrk411461gxsvvitduiy/deployments/cl6l2mhvq280081b01cg9g9nzw/analytics
        webserver_url: cosmicenergy.astronomer.run/dg9g9nzw?orgId=org_6UzgINU5tvBxxR4a
    alert_emails: []
```
